### ISSUE TITLE
Deploy jupyterhub-ssh

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/farallon-image#4]
From @trondkr:

> I don't think too many uses SSH (except perhaps me and @cgentemann) but SFTP I can see can be very useful. I think we want to upload large datasets to store on S3 or disk so that many can use these datasets when running code in the cloud. For me, being able to run notebooks on farallon.2i2c.cloud through pycharm would be awesome

So let's deploy [jupyterhub-ssh](https://github.com/yuvipanda/jupyterhub-ssh)

TODO:

## Phase 1: Get jupyterhub-ssh working

- [ ] Get latest version of jupyterhub-ssh (published in [this YAML file](https://yuvipanda.github.io/jupyterhub-ssh/index.yaml))
- [ ] Add it to `hub/requirements.yaml` so it gets pulled in as a dependency
- [ ] Set `jupyterhub-ssh.hubUrl` to full URL for each hub (`deployments/ohw/config/staging.yaml`, `deployments/ohw/config/prod.yaml`, `deployments/farallon/config/staging.yaml`, `deployments/farallon/config/prod.yaml`)
- [ ] Generate a private key for each hub (with `ssh-keygen -f <some-name>`), and copy it to `jupyterhub-ssh.hostKey` in the secret files for each hub (`deployments/ohw/secrets/staging.yaml`, etc). Use `sops <filename>` to edit the secret file - it will open in an editor.
- [ ] (temporarily) set `ssh.service.type` to `LoadBalancer` to get an external IP
- [ ] Disable sftp (temporarily) by setting `sftp.enabled` to `false`
- [ ] Deploy this to staging, and test out sshing in with the public IP the load balancer gets!

## Phase 2: Get jupyterhub-ssh working with the same URL as hub

Instead of sshing in with a separate domain / URL, we want users to ssh in with the *same* URL as the hub. This is doable since ssh listens on port 22, and `traefik` can proxy that too.

- [ ] Tell the proxy-public service to accept traffic on port 22 as well, by specifying `jupyterhub.proxy.extraPorts` - https://github.com/berkeley-dsep-infra/datahub/blob/staging/hub/values.yaml#L49. Should target port 8022, since we'll make traefik listen on that port for proxying to our jupyterhub-ssh service
- [ ] Tell traefik to proxy incoming traffic on port `8022` to the `jupyterhub-ssh` service on port 22. See sections under `jupyterhub.proxy.traefik.extraDynamicConfig.tcp` in https://github.com/berkeley-dsep-infra/datahub/blob/staging/hub/values.yaml#L78. 
- [ ] Allow ingress traffic from traefik into our ssh servers, by adding [these labels](https://github.com/berkeley-dsep-infra/datahub/blob/staging/hub/values.yaml#L69) to our traefik pod
- [ ] Allow ingress traffic *into* traefik from the outside, with [these network policy changes](https://github.com/berkeley-dsep-infra/datahub/pull/1947)

This should let you ssh in with the same domain as the hub!

Once done, you wanna clean up the external IP for the ssh service:
- [ ] Set `jupyterhub-ssh.ssh.service.type` to '`ClusterIP`. You might have to manually delete the `jupyterhub-ssh` service before deploying this, since helm might not like downgrading from `LoadBalancer` to `ClusterIP` type service
(More to come)
